- name: Install PostgreSQL
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql
    state: present

- name: Start PostgreSQL
  become: true
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
    enabled: true

- name: Check if checksumming is enabled
  become: true
  become_user: postgres
  ansible.builtin.command:
    cmd: psql --tuples-only -c 'SHOW data_checksums'
  changed_when: false
  register: checksums_status

- name: Enable checksums
  when: "'off' in checksums_status.stdout"
  block:
    - name: Stop PostgreSQL
      become: true
      ansible.builtin.systemd_service:
        name: postgresql
        state: stopped

    - name: Enable checksums
      become: true
      ansible.builtin.shell:
        cmd: /usr/lib/postgresql/*/bin/pg_checksums --pgdata /var/lib/postgresql/*/main/ --enable
      register: pg_checksums
      changed_when: pg_checksums.rc != 0 or "checksums enabled in cluster" in pg_checksums.stdout.lower()

    - name: Start PostgreSQL
      become: true
      ansible.builtin.systemd_service:
        name: postgresql
        state: started
        enabled: true
