- name: "Reload systemd"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Restart Prowlarr"
  become: true
  ansible.builtin.systemd_service:
    name: prowlarr.service
    state: restarted
