- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd

- name: Add hostname to /etc/hosts
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE HOSTNAME LOCALHOST"
    block: "127.0.0.1 {{ hostname }}"

- name: Remove passwordless sudoer for non-existing user
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent

- name: "Install essentials"
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - vim
      - tree
      - htop
      - iftop
      - iotop
      - dnsutils
      - needrestart
      - acl # Useful to `become` another unprivileged user
      - logrotate
    state: present

- name: "Configure unattended-upgrades"
  become: true
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/55custom-unattended-upgrades-email
    owner: root
    group: root
    mode: '644'

- name: "Color ls"
  become: true
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    marker: "# {mark} ANSIBLE COLOR LS"
    append_newline: true
    prepend_newline: true
    block: |
      export LS_OPTIONS='--color=auto'
      eval "$(dircolors)"
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'

- name: "Color root shell"
  become: true
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    marker: "# {mark} ANSIBLE ROOT PS1"
    append_newline: true
    prepend_newline: true
    block: export PS1='\[\e[1;31m\]\u@\h\[\e[1;0m\]:\[\e[1;34m\]\w\[\e[31m\]\$\[\e[0m\] '

- name: "Generate MOTD banner"
  ansible.builtin.shell:
    cmd: 'figlet {{ ansible_hostname | quote }} -f slant -w 120 | lolcat --force-color --seed {{ 65535 | random(seed=inventory_hostname) }}'
  delegate_to: localhost
  become: false
  register: motd
  changed_when: motd.rc != 0
  ignore_errors: true

- name: "Copy MOTD banner"
  become: true
  ansible.builtin.template:
    src: 00-banner.j2
    dest: /etc/update-motd.d/00-banner
    mode: "755"
  when: not motd.failed
