# - name: Add deb.sury.org repository signing key
#   become: true
#   ansible.builtin.get_url:
#     url: https://packages.sury.org/apt.gpg
#     dest: /usr/share/keyrings/deb.sury.org-php.gpg
#     owner: root
#     group: root
#     mode: "644"
#     checksum: sha256:d63c11bc5067b1849c6a42a2d061916ba7c07632d4c0dbda4789d66fb263a285

- name: Add deb.sury.org repository signing keys
  become: true
  ansible.builtin.apt:
    deb: https://packages.sury.org/debsuryorg-archive-keyring.deb
    state: present

- name: Add deb.sury.org APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Install PHP-FPM
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - php{{ item }}
      - php{{ item }}-fpm
    state: present
  loop: "{{ php_versions }}"

- name: Configure PHP timezone
  become: true
  ansible.builtin.lineinfile:
    path: /etc/php/{{ item[0] }}/{{ item[1] }}/php.ini
    search_string: date.timezone =
    line: date.timezone = Etc/UTC
  loop: "{{ php_versions | product(['fpm', 'cli']) | list }}"
