- name: Install dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - wireguard
    state: present

- name: Configure WireGuard peers
  become: true
  ansible.builtin.template:
    src: 99-wg0.netdev.j2
    dest: /etc/systemd/network/99-wg0.netdev
    owner: root
    group: systemd-network
    mode: "640"
  notify: "Reload systemd-networkd"

- name: Configure wg0 interface
  become: true
  ansible.builtin.template:
    src: 99-wg0.network.j2
    dest: /etc/systemd/network/99-wg0.network
    owner: root
    group: systemd-network
    mode: "640"
  notify: "Reload systemd-networkd"

- name: Enable systemd-networkd
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started
    enabled: true

- name: Copy UFW WireGuard application configuration
  become: true
  ansible.builtin.template:
    src: ufw-wireguard.j2
    dest: /etc/ufw/applications.d/nymous-wg
    owner: root
    group: root
    mode: "644"
  notify: "Reload UFW"

- name: Allow UFW WireGuard application
  become: true
  community.general.ufw:
    rule: allow
    name: nymous-wg

- name: Allow routing WireGuard packets between peers
  become: true
  community.general.ufw:
    route: true
    rule: allow
    interface_in: wg0
    interface_out: wg0

- name: Allow routing WireGuard packets to Internet
  become: true
  community.general.ufw:
    route: true
    rule: allow
    interface_in: wg0
    interface_out: ens3

- name: Configure UFW *nat rules for IP forwarding to ens3
  become: true
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    marker: "# {mark} ANSIBLE WIREGUARD RULES"
    prepend_newline: true
    append_newline: true
    insertbefore: "# Don't delete these required lines, otherwise there will be errors"
    block: |
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      {% for address in wireguard.addresses %}
      -A POSTROUTING -s {{ address }} -o ens3 -j MASQUERADE
      {% endfor %}
      COMMIT
  notify: "Reload UFW"

- name: Allow IPv4 forwarding
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ufw/sysctl.conf
    search_string: "net/ipv4/ip_forward=1"
    line: "net/ipv4/ip_forward=1"
  notify: "Reload UFW"
