# All configuration here can be applied with a reload of the unbound service

server:
  # send minimal amount of information to upstream servers to enhance privacy
  qname-minimisation: yes
  # addresses from the IP range that are allowed to connect to the resolver
  access-control: 127.0.0.1/8 allow
